/**
 * Database initialization and connection management
 *
 * SQLite + Drizzle ORM
 * DB location: userData/app.db
 *
 * Schema defined in shared/schema/*.ts (single source of truth)
 * Migrations generated by drizzle-kit
 * migrate() auto-creates tables on startup
 */

import { app } from 'electron'
import { drizzle } from 'drizzle-orm/better-sqlite3'
import { migrate } from 'drizzle-orm/better-sqlite3/migrator'
import Database from 'better-sqlite3'
import { join } from 'node:path'
import * as schema from 'shared/schema'

let db: ReturnType<typeof drizzle<typeof schema>> | null = null
let sqlite: Database.Database | null = null

function getDbPath(): string {
  const userDataPath = app.getPath('userData')
  return join(userDataPath, 'app.db')
}

/**
 * Get migrations directory
 * dev: project root/drizzle
 * production: resources/drizzle (via extraResources)
 */
function getMigrationsPath(): string {
  if (app.isPackaged) {
    return join(process.resourcesPath, 'drizzle')
  }
  return join(app.getAppPath(), 'drizzle')
}

export function initDatabase(): typeof db {
  if (db) return db

  const dbPath = getDbPath()
  console.log('[Database] Initializing:', dbPath)

  sqlite = new Database(dbPath)

  // SQLite configuration
  sqlite.pragma('journal_mode = WAL')
  sqlite.pragma('synchronous = NORMAL')
  sqlite.pragma('busy_timeout = 5000')
  sqlite.pragma('foreign_keys = ON')

  db = drizzle(sqlite, { schema })

  // Run migrations (idempotent)
  migrate(db, { migrationsFolder: getMigrationsPath() })

  console.log('[Database] Initialized')
  return db
}

export function getDatabase(): NonNullable<typeof db> {
  if (!db) {
    throw new Error('Database not initialized, call initDatabase() first')
  }
  return db
}

export function closeDatabase(): void {
  if (sqlite) {
    sqlite.close()
    sqlite = null
    db = null
    console.log('[Database] Connection closed')
  }
}
